echo during make

diff --git a/src/system/Makefile.in b/src/system/Makefile.in
--- a/src/system/Makefile.in
+++ b/src/system/Makefile.in
@@ -32,9 +32,6 @@ OBJSC =  System-IN.o timer.o files.o realtime.o \
 tcl/@SYST_FILES@/%.o: 
 	@cd tcl/@SYST_FILES@ && $(MAKE) $*.o
 
-#all     ::
-#	cd tcl/@SYST_FILES@ && $(MAKE) all
-
 include ../../Makefile.incl
 
 CFLAGS = $(CC_OPTIONS) 
@@ -43,9 +40,21 @@ include ../Make.lib
 
 timer.o: timer.c ../include/nsp/machine.h
 
-clean	::
-	cd tcl/@SYST_FILES@ ; make clean 
+SUBDIRS = tcl/@SYST_FILES@
 
-distclean :: clean 
+SILENT=$(findstring s,$(MFLAGS))
+DIR=
 
-
+clean distclean ::
+	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
+	for i in $(SUBDIRS) ;\
+	do \
+		(cd $$i && if test "x$(SILENT)" != "xs"; then echo "making $@ in $(DIR)$$i ";fi && \
+		$(MAKE) $(MFLAGS) DIR=$(DIR)$$i/ $@ ); \
+	   	IER=$$? &&\
+	   	case $$IER in\
+	    	0) ;;\
+	    	*) echo "Cannot make $@ in sub directory $$d";\
+	       	  exit $$IER;;\
+	   	esac;\
+	done
