updates

diff --git a/demos/graphics/Makefile b/demos/graphics/Makefile
--- a/demos/graphics/Makefile
+++ b/demos/graphics/Makefile
@@ -7,27 +7,17 @@ CFLAGS = $(CC_OPTIONS)
 
 SUBDIRS = libdemo
 
-all:: 
+all clean distclean ::
 	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
 	for i in $(SUBDIRS) ;\
 	do \
-		(cd $$i ; echo "making all in demos/graphics/$$i..."; \
-		$(MAKE) $(MFLAGS) all); \
-	done
-
-distclean::
-	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
-	for i in $(SUBDIRS) ;\
-	do \
-		(cd $$i ; echo "making distclean in demos/graphics/$$i..."; \
-		$(MAKE) $(MFLAGS)  distclean); \
-	done
-
-clean::
-	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
-	for i in $(SUBDIRS) ;\
-	do \
-		(cd $$i ; echo "making clean demos/graphics/$$i..."; \
-		$(MAKE) $(MFLAGS) clean); \
+		(cd $$i && echo "making $@ in demos/graphics/$$i " && \
+		$(MAKE) $(MFLAGS) -s $@ ); \
+	   	IER=$$? &&\
+	   	case $$IER in\
+	    	0) ;;\
+	    	*) echo "Cannot make $@ in sub directory $$d";\
+	       	  exit $$IER;;\
+	   	esac;\
 	done
 
diff --git a/demos/gtk2/Makefile b/demos/gtk2/Makefile
--- a/demos/gtk2/Makefile
+++ b/demos/gtk2/Makefile
@@ -7,27 +7,16 @@ CFLAGS = $(CC_OPTIONS)
 
 SUBDIRS = libbase libplus
 
-all:: 
+all clean distclean ::
 	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
 	for i in $(SUBDIRS) ;\
 	do \
-		(cd $$i ; echo "making all in macros/scicos_blocks/$$i..."; \
-		$(MAKE) $(MFLAGS) all); \
+		(cd $$i && echo "making $@ in demos/$$i " && \
+		$(MAKE) $(MFLAGS) -s $@ ); \
+	   	IER=$$? &&\
+	   	case $$IER in\
+	    	0) ;;\
+	    	*) echo "Cannot make $@ in sub directory $$d";\
+	       	  exit $$IER;;\
+	   	esac;\
 	done
-
-distclean::
-	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
-	for i in $(SUBDIRS) ;\
-	do \
-		(cd $$i ; echo "making distclean in macros/scicos_blocks/$$i..."; \
-		$(MAKE) $(MFLAGS)  distclean); \
-	done
-
-clean::
-	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
-	for i in $(SUBDIRS) ;\
-	do \
-		(cd $$i ; echo "making clean in macros/scicos_blocks/$$i..."; \
-		$(MAKE) $(MFLAGS) clean); \
-	done
-
diff --git a/macros/Makefile b/macros/Makefile
--- a/macros/Makefile
+++ b/macros/Makefile
@@ -6,30 +6,19 @@ include $(TOP)/Makefile.incl
 CFLAGS = $(CC_OPTIONS) 
 
 SUBDIRS =  graphics miscellaneous system statistics linalg calpol
-SUBDIRS_CLEAN =  graphics miscellaneous system statistics linalg calpol
 
-all:: 
+all clean distclean ::
 	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
 	for i in $(SUBDIRS) ;\
 	do \
-		(cd $$i ; echo "making all in macros/$$i..."; \
-		$(MAKE) $(MFLAGS) all); \
-	done
-
-distclean::
-	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
-	for i in $(SUBDIRS_CLEAN) ;\
-	do \
-		(cd $$i ; echo "making distclean in macros/$$i..."; \
-		$(MAKE) $(MFLAGS)  distclean); \
-	done
-
-clean::
-	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
-	for i in $(SUBDIRS_CLEAN) ;\
-	do \
-		(cd $$i ; echo "making clean in macros/$$i..."; \
-		$(MAKE) $(MFLAGS) clean); \
+		(cd $$i && echo "making $@ in demos/$$i " && \
+		$(MAKE) $(MFLAGS) -s $@ ); \
+	   	IER=$$? &&\
+	   	case $$IER in\
+	    	0) ;;\
+	    	*) echo "Cannot make $@ in sub directory $$d";\
+	       	  exit $$IER;;\
+	   	esac;\
 	done
 
 DESTDIR=$(prefix)/lib/nsp
