updates

diff --git a/macros/Makefile b/macros/Makefile
--- a/macros/Makefile
+++ b/macros/Makefile
@@ -5,15 +5,14 @@ include $(TOP)/Makefile.incl
 
 CFLAGS = $(CC_OPTIONS) 
 
-SUBDIRS =  graphics miscellaneous system statistics linalg calpol ast \
-	auto-sci \
+WIP=	auto-sci \
 	control-sci \
 	elementary-sci \
 	linalg-sci \
 	optim-sci \
 	robust-sci \
 
-
+SUBDIRS =  graphics miscellaneous system statistics linalg calpol ast $(WIP)
 
 all clean distclean ::
 	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
@@ -42,5 +41,34 @@ install::
 	@echo "installing macros files"
 	@$(TOP)/config/install-sh -d $(DESTDIR)/macros
 	@tar   cf - --exclude CVS . | ( cd $(DESTDIR)/macros ; tar xfp - )
+
+
+up	:
+	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
+	for i in $(WIP) ;\
+	do \
+		(cd $$i && echo "making $@ in macros/$$i " && \
+		cvs up ); \
+	   	IER=$$? &&\
+	   	case $$IER in\
+	    	0) ;;\
+	    	*) echo "Cannot make $@ in sub directory $$d";\
+	       	  exit $$IER;;\
+	   	esac;\
+	done
+
+commit	:
+	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
+	for i in $(WIP) ;\
+	do \
+		(cd $$i && echo "making $@ in macros/$$i " && \
+		cvs commit -m updates ); \
+	   	IER=$$? &&\
+	   	case $$IER in\
+	    	0) ;;\
+	    	*) echo "Cannot make $@ in sub directory $$d";\
+	       	  exit $$IER;;\
+	   	esac;\
+	done
 
 
